- name: understand vars preference
  hosts: local
  connection: local
  vars:
    GREETING: "Hello from play"
  # vars_files:
  # - course.yaml
  # vars_prompt:
  # - name: GREETING
  #   prompt: please enter the greeting
  #   private: false
  tasks:
  - name: print the GREETING
    # vars:
    #   GREETING: "hello from Task"
    ansible.builtin.debug:
      msg: "{{ GREETING }}"

# 1. command line or args
# 2. Task 
# 3. Files  
# 4. prompt  
# 5. play 
# 6. inventory