- name: playbook control using ansible facts
  hosts: frontend
  become: true
  tasks:
  - name: install nginx if redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: install nginx if debian
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"