- name: install packages
  hosts: frontend
  become: yes 
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.installed }}"
    loop:
    - { name: 'nginx', state: 'installed' } 
    - { name: 'mysql', state: 'absent' }
    - { name: 'zip', state: 'absent' } 