- name: functions
  hosts: local
  connection: local
  vars:
    persons: "raman,ammu,siva,krish"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "{{ person | default('deena') }}"
    
  - name: print names 
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',')}}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10HRs
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "course info: {{ course | dict2items }}"

  